module.exports={
    publicPath:'./',
    configureWebpack:{
        resolve:{
         alias: {
            'assets':'@/assets',
            'common':'@/common',
            'components':'@/components',
            'network':'@/network',
            'views':'@/views'
            }
        }
    },
      devServer:{
        proxy:{
            '/api':{
                target:'http://127.0.0.1:3001/api',
                ws:true,
                changeOrigin:true,
                pathRewrite:{
                    '^/api':''
                }
            }
        }
    }
}